// Renders site pages from the JSON in /content.
// Used by build.js (static output) and edit.js (same markup + edit hooks).
// Anything editable is tagged with data-edit-text / data-edit-media="<doc>#<path>"
// only when opts.edit is true, so the published HTML stays clean.

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const CONTENT = path.join(ROOT, 'content');
const PLACEHOLDER = 'assets/placeholder.jpg';
const LIBRARY = path.join(ROOT, 'library');
const MARKER = '<!-- generated by tools/build.js from /content — edit with `node tools/edit.js` -->';

// ---------------------------------------------------------------- library
// library/<name>.json: { name, props: { Prop: [values] }, variants: [{ props, tree }] }
// library/_presets.json: the Section + Container wrapped around a new instance.

function loadLibrary() {
  const lib = {};
  for (const f of fs.readdirSync(LIBRARY)) {
    if (!f.endsWith('.json') || f.startsWith('_')) continue;
    const def = JSON.parse(fs.readFileSync(path.join(LIBRARY, f), 'utf8'));
    lib[def.name] = def;
  }
  return lib;
}

function loadPresets() {
  const { ['//']: _, ...presets } = JSON.parse(fs.readFileSync(path.join(LIBRARY, '_presets.json'), 'utf8'));
  return presets;
}

function findVariant(def, chosen = {}) {
  return def.variants.find(v => Object.entries(v.props).every(([k, val]) => chosen[k] === val)) || def.variants[0];
}

function slotCount(tree) {
  let max = -1;
  (function walk(n) {
    if (n.type === 'media' && Number.isInteger(n.slot)) max = Math.max(max, n.slot);
    (n.children || []).forEach(walk);
  })(tree);
  return max + 1;
}

function newSection(component, variant) {
  const { section, container } = loadPresets();
  return { ...section, children: [{ ...container, children: [
    { type: 'instance', component, variant, content: { media: [] } },
  ] }] };
}

// First component instance inside a section (sections hold one for now)
function findInstance(node, keyPath = []) {
  if (node.type === 'instance') return { node, keyPath };
  for (const [i, child] of (node.children || []).entries()) {
    const hit = findInstance(child, [...keyPath, 'children', String(i)]);
    if (hit) return hit;
  }
  return null;
}

// ---------------------------------------------------------------- data

function readJSON(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function loadSite() {
  const site = readJSON(path.join(CONTENT, 'site.json'));
  const dir = path.join(CONTENT, 'projects');
  const slugs = fs.readdirSync(dir)
    .filter(f => f.endsWith('.json') && !f.startsWith('_'))
    .map(f => f.replace(/\.json$/, ''));
  const order = site.projectOrder || [];
  slugs.sort((a, b) => {
    const ia = order.indexOf(a), ib = order.indexOf(b);
    if (ia === -1 && ib === -1) return a.localeCompare(b);
    if (ia === -1) return 1;
    if (ib === -1) return -1;
    return ia - ib;
  });
  const projects = slugs.map(slug => ({ slug, ...readJSON(path.join(dir, slug + '.json')) }));
  return { site, projects };
}

// ---------------------------------------------------------------- helpers

const esc = s => String(s ?? '')
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

function ctx(opts, prefix) {
  const edit = !!opts.edit;
  return {
    p: prefix,
    edit,
    // data-edit-text attribute
    t: (doc, key) => edit ? ` data-edit-text="${doc}#${key}"` : '',
    // data-edit-media attribute (+ empty-state class)
    m: (doc, key, media) => edit
      ? ` data-edit-media="${doc}#${key}"${media && media.src ? '' : ' data-empty'}`
      : '',
  };
}

function img(c, media, { lazy = true } = {}) {
  const src = media && media.src ? media.src : PLACEHOLDER;
  return `<img src="${c.p}${esc(src)}" alt="${esc(media && media.alt)}"${lazy ? ' loading="lazy"' : ''}>`;
}

function tags(c, doc, list, base = 'tags') {
  return `<ul class="tags">
${(list || []).map((tag, i) =>
  `                  <li class="tag tag--${esc(tag.color || 'orange')}"${c.t(doc, `${base}.${i}.label`)}>${esc(tag.label)}</li>`).join('\n')}
                </ul>`;
}

function projectHref(c, slug) {
  return `${c.p}projects/${slug}.html`;
}

// ---------------------------------------------------------------- chrome

function head({ title, description }, c) {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(description)}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Dela+Gothic+One&family=Inter:wght@400;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="${c.p}css/styles.css">${c.edit ? `
  <link rel="stylesheet" href="/tools/editor/editor.css">` : ''}
</head>`;
}

function header(c, projects, currentSlug) {
  const portfolio = projects.map(pr =>
    `              <li><a class="nav-link" href="${projectHref(c, pr.slug)}"${pr.slug === currentSlug ? ' aria-current="page"' : ''}>${esc(pr.title)}</a></li>`).join('\n');
  return `  <header class="site-header" data-sc-scheme="scheme-1">
    <div class="site-header__inner">
      <div class="site-header__bar">
        <a class="site-logo" href="${c.p || './'}" aria-label="Phil Inge — home">
          <img src="${c.p}assets/logo.svg" width="312.458" height="50.9614" alt="Phil Inge">
        </a>
        <button class="site-header__toggle" type="button" aria-expanded="false" aria-controls="site-nav" aria-label="Open menu">
          <span></span><span></span>
        </button>
        <nav class="site-nav" id="site-nav" aria-label="Main">
          <div class="site-nav__col">
            <a class="site-nav__heading" href="${c.p}projects/">Portfolio</a>
            <ul class="site-nav__links">
${portfolio}
            </ul>
          </div>
          <div class="site-nav__col">
            <p class="site-nav__heading">Tools</p>
            <ul class="site-nav__links">
              <li><a class="nav-link" href="#">Brand Aligner</a></li>
              <li><a class="nav-link" href="#">Vibe Dialer</a></li>
              <li><a class="nav-link" href="#">Message Maker</a></li>
              <li><a class="nav-link" href="#">Builder</a></li>
            </ul>
          </div>
          <div class="site-nav__col">
            <p class="site-nav__heading">Services</p>
            <ul class="site-nav__links">
              <li><a class="nav-link" href="#">Logo Design</a></li>
              <li><a class="nav-link" href="#">Visual Identity Design</a></li>
              <li><a class="nav-link" href="#">Website Design</a></li>
              <li><a class="nav-link" href="#">Integrated Visual Brand Systems</a></li>
            </ul>
          </div>
          <div class="site-nav__col">
            <p class="site-nav__heading">Sessions</p>
            <ul class="site-nav__links">
              <li><a class="nav-link" href="#">Learn</a></li>
              <li><a class="nav-link" href="#">Build</a></li>
              <li><a class="nav-link" href="#">Consult</a></li>
            </ul>
          </div>
        </nav>
      </div>
      <hr class="site-header__rule">
    </div>
  </header>`;
}

function footer(c) {
  return `  <footer class="site-footer" data-sc-scheme="scheme-3">
    <div class="site-footer__upper">
      <address class="site-footer__address">
        <span>Cahoots Studio</span>
        <span>1234 Street Name</span>
        <span>Denver, CO 80202</span>
      </address>
      <nav class="site-footer__nav" aria-label="Footer">
        <div class="site-footer__col">
          <p class="site-footer__heading">Column One</p>
          <ul>
            <li><a href="#">Link One</a></li>
            <li><a href="#">Link Two</a></li>
            <li><a href="#">Link Three</a></li>
          </ul>
        </div>
        <div class="site-footer__col">
          <p class="site-footer__heading">Column Two</p>
          <ul>
            <li><a href="#">Link Four</a></li>
            <li><a href="#">Link Five</a></li>
            <li><a href="#">Link Six</a></li>
          </ul>
        </div>
        <div class="site-footer__col">
          <p class="site-footer__heading">Column Three</p>
          <ul>
            <li><a href="#">Link Seven</a></li>
            <li><a href="#">Link Eight</a></li>
            <li><a href="#">Link Nine</a></li>
          </ul>
        </div>
      </nav>
    </div>

    <div class="sc-logo" role="img" aria-label="Supercomponent">
      <span class="sc-logo__mark"><img src="${c.p}assets/sc-mark.svg" width="48" height="48" alt=""></span>
      <img class="sc-logo__wordmark" src="${c.p}assets/sc-wordmark.svg" width="546.913" height="30.486" alt="">
    </div>

    <hr class="site-footer__rule">

    <div class="site-footer__lower">
      <div class="site-footer__credits">
        <p>Dreamed Designed and build by Cahoots Studio</p>
        <p>© 2026 Cahoots Studio</p>
      </div>
      <ul class="site-footer__subnav">
        <li><a href="#">Privacy Policy</a></li>
        <li><a href="#">Terms of Service</a></li>
        <li><a href="#">Accessibility</a></li>
        <li><a href="#">Cookie Settings</a></li>
      </ul>
    </div>
  </footer>

  <script src="${c.p}js/nav.js" defer></script>${c.edit ? `
  <script src="/tools/editor/editor.js" defer></script>` : ''}
</body>
</html>
`;
}

function page(meta, c, projects, currentSlug, main) {
  return `${head(meta, c)}
<body>
${c.edit ? '' : MARKER + '\n'}
${header(c, projects, currentSlug)}

  <main>
${main}
  </main>

${footer(c)}`;
}

// ---------------------------------------------------------------- pages

function renderHome(opts = {}) {
  const { site, projects } = loadSite();
  const c = ctx(opts, '');
  const h = site.home;
  const tiles = projects.map(pr => {
    const doc = `projects/${pr.slug}`;
    const tagged = pr.home && pr.home.showTags;
    return `          <li>
            <a class="project-tile${tagged ? ' project-tile--tagged' : ''}" href="${projectHref(c, pr.slug)}">
              <div class="project-tile__media"${c.m(doc, 'cover', pr.cover)}>${img(c, pr.cover)}</div>
              <div class="project-tile__meta">${tagged ? `
                ${tags(c, doc, pr.tags)}` : ''}
                <h2 class="project-tile__title"><span${c.t(doc, 'title')}>${esc(pr.title)}</span> <span class="project-tile__arrow" aria-hidden="true"></span></h2>
              </div>
            </a>
          </li>`;
  }).join('\n');

  return page(h, c, projects, null, `    <section class="hero">
      <div class="container">
        <h1 class="hero__headline"${c.t('site', 'home.headline')}>${esc(h.headline)}</h1>
      </div>
    </section>

    <section class="portfolio" aria-label="Selected work">
      <div class="container">
        <ul class="portfolio__grid">
${tiles}
        </ul>
      </div>
    </section>`);
}

function renderProjects(opts = {}) {
  const { site, projects } = loadSite();
  const c = ctx(opts, '../');
  const pg = site.projectsPage;
  const rows = projects.map(pr => {
    const doc = `projects/${pr.slug}`;
    return `          <li>
            <a class="project-row" href="${pr.slug}.html">
              <h2 class="project-row__title"${c.t(doc, 'title')}>${esc(pr.title)}</h2>
              <div class="media project-row__media"${c.m(doc, 'cover', pr.cover)}>${img(c, pr.cover)}</div>
              <div class="project-summary">
                ${tags(c, doc, pr.tags)}
                <p${c.t(doc, 'summary')}>${esc(pr.summary)}</p>
              </div>
            </a>
          </li>`;
  }).join('\n');

  return page(pg, c, projects, null, `    <section class="page-intro">
      <div class="container page-intro__row">
        <h1 class="page-intro__title"${c.t('site', 'projectsPage.heading')}>${esc(pg.heading)}</h1>
        <div class="project-summary">
          ${tags(c, 'site', pg.tags, 'projectsPage.tags')}
          <p${c.t('site', 'projectsPage.intro')}>${esc(pg.intro)}</p>
        </div>
      </div>
    </section>

    <section class="project-list" aria-label="All projects">
      <div class="container">
        <ul class="project-list__stack">
${rows}
        </ul>
      </div>
    </section>`);
}

// ---------------------------------------------------------------- layout tree
// Section > Container/Column > Component > Block. Every wrapper is a flexbox:
//   direction  row | column (default)
//   width/height  "fill" | "fill <weight>" | "hug" | fixed length ("$token" or "348px")
//   gap, padding ({x,y} or one value), align, justify, wrap, aspect, max, background
//   mobile: "stack" → becomes a single column under 900px
// "$name" resolves to var(--name), so every value can point at a design variable.

const tok = v => typeof v === 'string' && v.startsWith('$') ? `var(--${v.slice(1)})` : v;

function sizing(val, dim, isMain) {
  if (!val) return {};
  const [mode, weight] = String(val).trim().split(/\s+/);
  if (mode === 'fill') return isMain ? { flex: `${weight || 1} 1 0` } : { 'align-self': 'stretch' };
  if (mode === 'hug') return isMain ? { flex: 'none' } : { 'align-self': 'flex-start' };
  return isMain ? { flex: 'none', [dim]: tok(val) } : { [dim]: tok(val) };
}

function nodeStyle(n, parentDir) {
  const st = {};
  if (n.direction === 'row') st['flex-direction'] = 'row';
  if (n.gap) st.gap = tok(n.gap);
  if (n.padding) {
    st.padding = typeof n.padding === 'object'
      ? `${tok(n.padding.y || 0)} ${tok(n.padding.x || 0)}`
      : tok(n.padding);
  }
  if (n.align) st['align-items'] = n.align;
  if (n.justify) st['justify-content'] = n.justify;
  if (n.wrap) st['flex-wrap'] = 'wrap';
  if (n.aspect) st['aspect-ratio'] = n.aspect.replace('/', ' / ');
  if (n.background) st.background = tok(n.background);
  if (n.max) Object.assign(st, { width: '100%', 'max-width': tok(n.max), 'margin-inline': 'auto' });
  if (parentDir) {
    Object.assign(st, sizing(n.width, 'width', parentDir === 'row'));
    Object.assign(st, sizing(n.height, 'height', parentDir === 'column'));
  }
  const css = Object.entries(st).map(([k, v]) => `${k}: ${v}`).join('; ');
  return css ? ` style="${esc(css)}"` : '';
}

function nodeAttrs(n) {
  return (n.direction === 'row' ? ' data-dir="row"' : '') + (n.mobile === 'stack' ? ' data-m="stack"' : '');
}

// env: { c, doc, lib, path (page-tree key path), instance: { content, path } }
function renderNode(n, env, parentDir, depth) {
  const pad = '  '.repeat(depth);
  const dir = n.direction === 'row' ? 'row' : 'column';
  const kids = (list, childEnv = env) => (list || [])
    .map((ch, i) => renderNode(ch, { ...childEnv, path: `${childEnv.path}.children.${i}` }, dir, depth + 1))
    .join('\n');

  switch (n.type) {
    case 'instance': {
      const def = env.lib[n.component];
      if (!def) throw new Error(`Unknown component "${n.component}" in ${env.doc}`);
      const { tree } = findVariant(def, n.variant);
      return renderNode(tree, { ...env, instance: { content: n.content || {}, path: env.path } }, parentDir, depth);
    }
    case 'media': {
      const m = env.instance && env.instance.content.media ? env.instance.content.media[n.slot] || null : null;
      const target = `${env.instance.path}.content.media.${n.slot}`;
      return `${pad}<div class="media sc-media"${nodeStyle(n, parentDir)}${env.c.m(env.doc, target, m)}>${img(env.c, m)}</div>`;
    }
    case 'section':
    case 'container':
    case 'column':
    case 'component': {
      const tag = n.type === 'section' ? 'section' : 'div';
      return `${pad}<${tag} class="sc-${n.type}"${nodeAttrs(n)}${nodeStyle(n, n.type === 'section' ? null : parentDir)}>
${kids(n.children)}
${pad}</${tag}>`;
    }
    default:
      throw new Error(`Unknown node type "${n.type}" in ${env.doc}`);
  }
}

function renderSections(c, doc, sections) {
  const lib = loadLibrary();
  return (sections || []).map((sec, i) => {
    const html = renderNode(sec, { c, doc, lib, path: `sections.${i}` }, null, 2);
    // Tag the outer <section> so edit mode can attach section controls
    return c.edit ? html.replace('<section ', `<section data-edit-section="${i}" `) : html;
  }).join('\n\n');
}

// Data the editor needs to build section controls (edit mode only)
function editData(doc, sections) {
  const lib = loadLibrary();
  return {
    doc,
    library: Object.values(lib).map(d => ({ name: d.name, props: d.props })),
    sections: (sections || []).map(sec => {
      const hit = findInstance(sec);
      return hit ? { component: hit.node.component, variant: hit.node.variant || {} } : null;
    }),
  };
}

function renderProject(slug, opts = {}) {
  const { projects } = loadSite();
  const pr = projects.find(x => x.slug === slug);
  if (!pr) return null;
  const c = ctx(opts, '../');
  const doc = `projects/${slug}`;
  const meta = {
    title: `${pr.title} — Phil Inge`,
    description: pr.summary,
  };
  const sections = renderSections(c, doc, pr.sections) + (c.edit
    ? `\n  <script type="application/json" id="sc-edit-data">${JSON.stringify(editData(doc, pr.sections)).replace(/</g, '\\u003c')}</script>`
    : '');

  return page(meta, c, projects, slug, `    <section class="project-hero">
      <div class="container">
        <div class="project-hero__row">
          <h1 class="project-hero__title"${c.t(doc, 'title')}>${esc(pr.title)}</h1>
          <div class="project-summary">
            ${tags(c, doc, pr.tags)}
            <p${c.t(doc, 'summary')}>${esc(pr.summary)}</p>
          </div>
        </div>
        <div class="media project-hero__media"${c.m(doc, 'cover', pr.cover)}>${img(c, pr.cover, { lazy: false })}</div>
      </div>
    </section>

${sections}`);
}

module.exports = {
  ROOT, CONTENT, MARKER,
  loadSite, loadLibrary, findVariant, slotCount, newSection, findInstance,
  renderHome, renderProjects, renderProject,
};
