// Turns tokens/figma-variables.json (Figma variables, every mode) into css/tokens.css.
// Run: node tools/tokens.js
//
// The largest mode is the base (:root); each smaller mode only restates the
// values that change, inside a max-width media query. Names follow the Figma
// path: "Padding/Gap/Tiny" → --padding-gap-tiny. Aliases stay aliases.

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'tokens', 'figma-variables.json');
const OUT = path.join(ROOT, 'css', 'tokens.css');

const cssName = figmaPath => '--' + figmaPath.toLowerCase().replace(/[\s/]+/g, '-');

function cssValue(figmaPath, v) {
  if (v && typeof v === 'object' && v.alias) return `var(${cssName(v.alias)})`;
  if (typeof v === 'number') {
    if (/^Typeface\/Weight\//.test(figmaPath)) return String(v);
    return v === 0 ? '0' : `${v}px`;
  }
  if (/^Typeface\/Family\//.test(figmaPath)) return `"${v}"`;
  return String(v);
}

function build() {
  const data = JSON.parse(fs.readFileSync(SRC, 'utf8'));
  // Largest → smallest by breakpoint (don't trust key order: "1440" sorts first in JS)
  const modes = Object.keys(data.breakpoints).sort((a, b) => data.breakpoints[b] - data.breakpoints[a]);
  const vars = {};
  for (const col of Object.values(data.collections)) Object.assign(vars, col.variables);

  const decl = mode => Object.entries(vars).map(([p, byMode]) => [cssName(p), cssValue(p, byMode[mode])]);
  const block = (lines, indent) => lines.map(([k, v]) => `${indent}${k}: ${v};`).join('\n');

  let out = `/* Generated by tools/tokens.js from tokens/figma-variables.json — do not edit.
   Source: ${data.source} (exported ${data.exported})
   Modes → screen widths: ${modes.map((m, i) => `${m} ${data.breakpoints[m]}px+`).join(' · ')} */

/* ${modes[0]} */
:root {
${block(decl(modes[0]), '  ')}
}
`;
  let prev = Object.fromEntries(decl(modes[0]));
  for (let i = 1; i < modes.length; i++) {
    const mode = modes[i];
    const below = data.breakpoints[modes[i - 1]];
    const changed = decl(mode).filter(([k, v]) => prev[k] !== v);
    prev = { ...prev, ...Object.fromEntries(changed) };
    if (!changed.length) continue;
    out += `
/* ${mode} */
@media (max-width: ${below - 0.02}px) {
  :root {
${block(changed, '    ')}
  }
}
`;
  }
  fs.writeFileSync(OUT, out);
  return { modes: modes.length, variables: Object.keys(vars).length };
}

module.exports = { build };

if (require.main === module) {
  const r = build();
  console.log(`css/tokens.css: ${r.variables} variables across ${r.modes} modes`);
}
